TEST_VALUE:
  name: 'dev_cookie'

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3004cf53bb8900b
  FEISHU_APP_SECRET: ll3pK69FRSv9wN8C3Z6kM3puJ8BwccHl

FEISHU_TOKEN_CACHE:
  APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
  TENANT_TOKEN_CACHE_KEY: TENANT_TOKEN_CACHE_KEY

REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
  auth: ""       # redis 连接密码
  db: "0"           # redis 数据库

MONGODB_CONFIG:
  name: "fast_gateway_test"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.6.1"   # 数据库链接地址
  username: "root"                   # 数据库链接用户名
  password: "root"                 # 数据库链接密码
  database: "fast_gateway_test"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能

MYSQL_CONFIG:
  name: "user-test"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "xxxx"
  password: "123456"
  database: "user-test"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true