TEST_VALUE:
  name: 'dev_cookie'

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a3004cf53bb8900b
  FEISHU_APP_SECRET: ll3pK69FRSv9wN8C3Z6kM3puJ8BwccHl

FEISHU_TOKEN_CACHE:
  APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY
  TENANT_TOKEN_CACHE_KEY: TENANT_TOKEN_CACHE_KEY